Sprint 17
slenbder/Tracker pull request #8
Opened 2024-09-25 12:50 UTC by slenbder

Итак, этому спринту было выделено гораздо больше времени и сил, чем на все предыдущие. Уделил больше внимания UI и его соответствию макету. Особенно много времени убил на сепараторы между ячейками фильтров, списка категорий - есть ли более изящное решение проблемы лишних сепараторов? Был бы рад узнать
А так в остальном я правда постарался над этим спринтом, надеюсь на этот раз будет победа с первого раза

2024-09-26 06:34 UTC, protos17 requested changes

2024-09-26 06:34 UTC, protos17 commented on Tracker/AnalyticService/AnalyticService.swift
> +        let configuration = YMMYandexMetricaConfiguration(apiKey: "39d2758b-ad7d-45a6-95be-f298354aeb4e")
apiKey рекомендую перенести в константы, а еще лучше, взять за правило, никогда ключи и пароли не хранить в репозитории

2024-09-26 06:34 UTC, protos17 commented on Tracker/CategoryViewController/CategoryViewController.swift
> +
Рекомендую оставлять не больше 1 отступа

2024-09-26 06:34 UTC, protos17 commented on Tracker/CoreData/DaysValueTransformer.swift
> +        return true
При возвращении значения одной строкой можно не писать слово return

2024-09-26 06:34 UTC, protos17 commented on Tracker/CoreData/TrackerCategoryStore.swift
>          let fetchRequest = NSFetchRequest<TrackerCoreData>(entityName: "TrackerCoreData")
"TrackerCoreData" рекомендую перенести в константы, используется часто по проекту

2024-09-26 06:34 UTC, protos17 commented on Tracker/CoreData/TrackerRecordStore.swift
> +        let trackerRecordCoreDataArray = try! managedContext.fetch(fetchRequest)
Рекомендую не использовать принудительное извлечение опционального значения. Рекомендую заменить try! на более безопасный try?

2024-09-26 06:34 UTC, protos17 commented on Tracker/CoreData/UIColorMarshalling.swift
>  import UIKit
При импорте UIKit можно не импортировать Foundation, потому что первый содержит в себе второй

2024-09-26 06:34 UTC, protos17 commented on Tracker/CreateNewEvent/CreateNewIrregularEventViewController.swift
> +        cancelButton.setTitle(localizedString(key:"cancelButton"), for: .normal)
Ключи key рекомендую хранить в константах, чтобы не писать его постоянно заново

2024-09-26 06:34 UTC, protos17 commented on Tracker/CreateNewHabit/NewHabitViewController.swift
> +            title = "Редактирование привычки"
Работу с текстом всегда рекомендую перенесить в отдельный файл. Это поможет легче менять при необходимости и полезно при добавлении локализации

2024-09-26 06:34 UTC, protos17 commented on TrackerTests/__Snapshots__/TrackerTests/testStatisticsViewController.1.png
Картинки с тестами рекомендую не сохранять. Они должны создаваться самостоятельно при первом запуске

2024-09-26 06:34 UTC, protos17 commented on Tracker/TrackerViewController/TrackerViewController.swift
> +        AnalyticsService.report(event: "open", params: ["screen": "Main"])
Рекомендую для всех параметров аналитики создать отдельный enum и использовать его

2024-09-26 06:34 UTC, protos17 commented on Tracker/TrackerViewController/TrackerViewController.swift
> +        let config = UIContextMenuConfiguration(actionProvider:  { _ in
Сильные ссылки в каждом замыкании ниже. Рекомендую здесь указать [weak self]

2024-09-26 06:34 UTC, protos17 commented on Tracker/TrackerViewController/TrackerViewController.swift
> +        let deleteAction = UIAlertAction(title: localizedString(key: "deleteButton"), style: .destructive) { _ in
Сильная ссылка, необходимо добавить [weak self]

2024-09-26 09:13 UTC, slenbder commented on Tracker/AnalyticService/AnalyticService.swift
> +        let configuration = YMMYandexMetricaConfiguration(apiKey: "39d2758b-ad7d-45a6-95be-f298354aeb4e")
Досадное упущение. Закинул ключ в отдельный файл и кинул его в гитигнор

2024-09-26 09:19 UTC, slenbder commented on Tracker/CategoryViewController/CategoryViewController.swift
> +
Поправил!

2024-09-26 09:20 UTC, slenbder commented on Tracker/CoreData/DaysValueTransformer.swift
> +        return true
Поправил!

2024-09-26 09:24 UTC, slenbder commented on Tracker/CoreData/TrackerRecordStore.swift
> +        let trackerRecordCoreDataArray = try! managedContext.fetch(fetchRequest)
Исправил!  Юзанул do-catch для явной обработки ошибок

2024-09-26 09:25 UTC, slenbder commented on Tracker/CoreData/UIColorMarshalling.swift
>  import UIKit
Исправил!

2024-09-26 09:37 UTC, slenbder commented on TrackerTests/__Snapshots__/TrackerTests/testStatisticsViewController.1.png
Добавил папку __Snapshot__ в игнор

2024-09-26 09:55 UTC, slenbder commented
Сначала испугался вылета ...а на деле пустяк. Проблема возникала из-за несоответствия между состоянием данных и обновлениями коллекции. Добавил метод, чтобы корректно обновить UICollectionView без несоответствий. Дело на 20 минут, вошел в Xcode и вышел.

Так же исправил ошибки, указанные в ПР.

Рекомендациями постараюсь заняться, когда на каникулах восстановлю режим сна, силы и нервы

2024-09-26 12:16 UTC, protos17 commented
> Итак, этому спринту было выделено гораздо больше времени и сил, чем на все предыдущие. Уделил больше внимания UI и его соответствию макету. Особенно много времени убил на сепараторы между ячейками фильтров, списка категорий - есть ли более изящное решение проблемы лишних сепараторов? Был бы рад узнать А так в остальном я правда постарался над этим спринтом, надеюсь на этот раз будет победа с первого раза

У тебя только новый коммит с удалением скриншотов и больше никаких новых изменений

2024-09-26 12:34 UTC, slenbder commented on Tracker/TrackerViewController/TrackerViewController.swift
> +        let deleteAction = UIAlertAction(title: localizedString(key: "deleteButton"), style: .destructive) { _ in
Исправил!

2024-09-26 12:42 UTC, slenbder commented
Да, я просто забыл запушить... Можно это не будет считаться попыткой? Иначе провалить спринт из-за такой мелочи - фатальная ошибка

2024-09-26 12:55 UTC, protos17 commented
> Да, я просто забыл запушить... Можно это не будет считаться попыткой? Иначе провалить спринт из-за такой мелочи - фатальная ошибка

Да мне кажется все хорошо будет, не переживай)

2024-09-27 07:11 UTC, protos17 approved these changes

2024-09-27 07:11 UTC, protos17 commented on Tracker/TrackerModels/CustomStatisticView.swift
Код стоит организовывать следующим образом:
Публичные переменные
IBOutlet
Приватные переменные
Методы жизненного цикла UIViewController
Публичные методы
Приватные методы
Подробнее почитать можно [тут](https://github.com/RedMadRobot/RMR-swift-style-guide#code-organization)

2024-10-12 13:30 UTC, merged